name: Build (dev)

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Installing Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      
      - name: Installing NPM packages
        run: npm ci
      
      - name: Building the app
        run: npm run build

      - name: Testing the build
        run: npm run test